apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: service-callee
  name: service-callee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-callee
  template:
    metadata:
      labels:
        app: service-callee
    spec:
      containers:
      - image: gcr.io/laputa/service-callee
        name: service-callee
        env:
        - name: RANDOM_HASH
          value: random
        - name: WAIT_BEFORE_SERVER_CLOSE
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-callee
  name: service-callee
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: service-callee
  type: ClusterIP
